### ISSUE TITLE
How to configure default/unknown virtual hosts?

### ISSUE THREAD

**Issue by ubershmekel** [containerize-my-server/reverse-proxy#3]
Hi @nknapp thank you for setting this repo up, it's awesome!

Currently what a user sees the first time they fire up the reverse-proxy in a browser is `404 page not found`. I'm also not sure how to intercept these for the raw ip address or unknown hosts used. E.g. `traefik.frontend.rule` should be empty?

This is more of a question than an issue, sorry about that.

**Comment by nknapp** [comment]
I don't know if this is possible. I have had a look throught [the documentation](https://docs.traefik.io/toml) of Træfik and could not find anything. If you find out and have a solution to this problem, feel free to create a PR.
